version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: beforeinstall.sh
      timeout: 300
  AfterInstall:
    - location: afterinstall.sh
      timeout: 300
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 300
  ApplicationStop:
    - location: applicationstop.sh
      runas: ignore_errors    
