version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: ignore_errors
  BeforeInstall:
    - location: beforeinstall.sh
      timeout: 300
  AfterInstall:
    - location: afterinstall.sh
      timeout: 300
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 300
